---
cache: pip
dist: xenial
addons:
  apt:
    update: true  # instruct travis-ci to always run apt-get before each build

language: python
python: 3.7

install:
  - pip install .[all]
script:
  - python setup.py test
after_success:
  # Report metrics, such as coverage
  - coverage xml --ignore-errors
  - bash <(curl -s https://codecov.io/bash)
