[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = """
    --doctest-modules
    --doctest-continue-on-failure
"""
doctest_optionflags = """
    NORMALIZE_WHITESPACE
    IGNORE_EXCEPTION_DETAIL
"""
testpaths = [
    'cylc/uiserver'
]
markers = [
    'integration: tests which run servers and try to connect to them'
]
