[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
# addopts = "--doctest-modules"
testpaths = [
    'cylc/'
]
collect_ignore = [
    'cylc/uiserver/jupyter_config.py'
]
